.TH argv_make(1) 2011-020-7 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man argv_make.1
.\" 2011-02-17 JoungKyun Kim <htt://oops.org>
.\" $Id: argv_make.3,v 1.4 2011-02-06 17:12:16 oops Exp $
.SH 이름
argv_make

.SH 사용법
.B #include <olibc/libarg.h>
.sp
.BI "char ** argv_make (char *stream, int *argc);"

.SH 라이브러리 링크
.B gcc source -loc
.br

.SH 설명
문자열을 공백문자[ \\n\\t]를 기준으로 배열로 변환을 한다. 쉽게 command line 의 명령행이 argv
변수로 되는 것과 동일하게 생각할 수 있다.

stream 은 입력할 문자열을 지정하며, argc 는 생성된 배열의 수가 반영이 된다.

.SH 반환값
성공시에 배열의 point가 반환이 되며, 실패시에 NULL이 반환된다. 생성된 배열은
ofree_array 함수로 메모리 해제를 해 주어야 한다.

.SH 예제
.nf
#include <olibc/libarg.h>

char * string = "arg1 arg2 arg3 \\"arg4 arg5\\"";
char ** argv;
char ** scan;
int argc, i;

argv = argv_make (string, &argc);

printf ("## 생성된 배열의 수 : %d\\n", argc);

for ( scan = argv, i=0; *scan != NULL; scan++, i++ ) {
    printf ("[%d] %s\\n", *scan);
}

ofree_array (argv);
.fi

.SH 참고
ofree_array(1)

.SH 작성
2004.02.19 김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
