.TH char2int(3) 2011-02-10 "Linux Manpage" "OOPS C Library's Manual"
.\" Process with
.\" nroff -man char2int.3
.\" 2011-03-04 JoungKyun Kim <htt://oops.org>
.\" $Id$
.SH NAME
char2int \- convert to integer from char

.SH SYNOPSIS
.B #include <olibc/libstring.h>
.sp
.BI "int char2int (const char c);"

.SH Link library
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
The
.BI char2int()
api convert to integer a character that is ascii between 48 and 57.
This api is similar the
.BI atoi()
api.

.TP
.B char c
.br
The input numeric character (character 0 \- 9)

.SH "RETURN VALUE"
Return an integer. If a charactor is out of ascii range between 48 and 57,
return \-1.

.SH EXAMPLE
.nf
#include <olibc/libstring.h>

int main (void) {
    char * str = "123";
    int no = 0,
        i = 0,
        x = 1,
        res = 0;

    for ( i=strlen(str) \- 1; i >= 0; i\-\- ) {
        if ( (no = char2int (str[i])) > 0 ) {
            res += (no * x);
            x *= 10;
        }
    }
    printf ("%d\\n", res);

    return 0;
}
.fi

.SH "SEE ALSO"
is_strint(3) str2double(3) str2long(3)

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
