.TH char2int(1) 2003-09-04 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man char2int.1
.\" 2003-09-04 JoungKyun Kim <htt://www.oops.org>
.SH 이름
char2int

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "int char2int(char c);"

.SH 설명
캐릭터를 int 형으로 변환한다.

.TP
.B c
.br
정수로 변경 할 캐릭터를 지정한다.

.SH 반환값
정수로 변환이 불가능 하면 -1을 반환한다.

.SH 예제
.nf
#include <olibc/libstring.h>

char *str = "123";
int no = 0, i = 0, x = 1, res = 0;

for (i=strlen(str) - 1; i >= 0; i--) {
  if ( (no = char2int (str[i])) > 0 ) {
    res += no;
    x * 10;
  }
}

printf ("%d\\n", res);
.fi

.SH 참조
check_int(1) str2double(1) str2long(1)

.SH 작성
2003.09.04 김정균 <http://www.oops.org>

.SH 버그
버그가 발견이 되면 http://www.oops.org 로 리포팅을 부탁한다.

.SH 저작권
BPL License v.1
.br
http://devel.oops.org/document/bpl 을 참고 하도록 한다.
