.TH check_int(1) 2004-02-19 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man check_int.1
.\" 2004-02-19 JoungKyun Kim <htt://oops.org>
.\" $Id: check_int.3,v 1.4 2009-10-29 13:24:33 oops Exp $
.SH 이름
check_int

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "int check_int(char c);"

.SH 라이브러리 링크
.B gcc source -l liboc
.br

또는

.B gcc source -l libolibc
.br

libolibc 를 정적으로 링크할 경우에는 LGPL2 에 근거하여 사용이 가능하며, liboc 를
정적으로 링크할 경우에는 BPL 에 근거한다.

.SH 설명
해당 캐릭터가 정수인지 아닌지를 체크한다.

.TP
.B c
.br
캐릭터를 지정한다.

.SH 반환값
정수이면 1을 반환하고, 아니면 0을 반환한다.

.SH 예제
.nf
#include <olibc/libstring.h>

char *str = "12c3";
int no = 0, i = 0, x = 1, res = 0;

for (i=strlen(str) - 1; i >= 0; i--) {
  if ( check_int (str[i]) ) {
    printf ("%c is int", str[i]);
  } else {
    printf ("%c is not int", str[i]);
  }
}
.fi

.SH 참조
char2int(1) str2double(1) str2long(1)

.SH 작성
2004.02.19 김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
