.TH convert_punycode(1) 2003-09-08 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man convert_punycode.1
.\" 2003-09-08 JoungKyun Kim <htt://www.oops.org>
.SH 이름
convert_punycode

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "char * convert_punycode (char * domain, int mode, int debug);"

.SH 설명
convert_punycode 함수는 com/net/org 에 사용이 되는 muitibyte 도메인의 punycode 변환을
위하여 사용이 된다.

이 함수를 사용하기 위해서는 olibc 빌드시에 iconv library 를 link 해 줘야 한다.

.TP
.B domain
.br
변환할 멀티바이트/punycode 도메인을 지정

.TP
.B mode
.br
0 을 지정하면, 멀티바이트 도메인을 punycode 로 변환하며, 1을 지정하면 punycode 도메인을
멀티바이트 도메인으로 변환한다.

.TP
.B debug
.br
debug 옵션

.SH 예제
.nf
#include <olibc/libstring.h>

char x[32] = "한글도메인.kr";
char y[64] = "xn--bj0bj3i97fq8o5lq.kr";

printf ("%s\\n", convert_punycode (x, 0, 1));
printf ("%s\\n", convert_punycode (y, 1, 1));
.fi

.SH 참조
convert_punycode(1)

.SH 작성
2003.09.04 김정균 <http://www.oops.org>

.SH 버그
버그가 발견이 되면 http://www.oops.org 로 리포팅을 부탁한다.

.SH 저작권
LGPL 2.1 License
