.TH convert_punycode(3) 2011-03-14 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man convert_punycode.3
.\" 2011-03-14 JoungKyun Kim <htt://oops.org>
.\" $Id: convert_punycode.3,v 1.9 2011-03-25 12:14:41 oops Exp $
.SH NAME
convert_punycode \- Convert between punycode and international domain.

.SH SYNOPSIS
.B #include <olibc/libidn.h>
.sp
.BI "char * convert_punycode_r (const char * src, bool mode, const char * charset)"

.SH "Link Library"
.B \-logc
or
.B \-lolibc
.br

The libraries are include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.

.SH DESCRIPTION
These apis convert to punycode from international domain or
convert to international domain from punycode

.TP
.B src
.br
International domain for converting

.TP
.B mode
.br
encode(set false) or decode(set true)

.TP
.B charset
.br
The character set of international domain

.SH "RETURN VALUE"
The pointer of converted domain. When occurs internal error,
.B convert punycode()
returns null. If the return string array pointer is not null,
the caller should deallocate this buffer using
.B free()

.SH EXAMPLE
.nf
#include <olibc/libidn.h>

int main (void) {
    char x[32] = "한글도메인.kr";
    char y[64] = "xn--bj0bj3i97fq8o5lq.kr";
	char * buf;

    buf = convert_punycode (x, false, "EUC-KR");
    if ( buf != NULL ) {
        printf ("%s\\n", buf);
        free (buf);
    }

    buf = convert_punycode (y, true, "EUC-KR");
    if ( buf != NULL ) {
        printf ("%s\\n", buf);
        free (buf);
    }

    return 0;
}
.fi

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
