.TH fileread(1) 2003-09-09 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man fileread.1
.\" 2003-09-09 JoungKyun Kim <htt://www.oops.org>
.\" $Id: fileread.3,v 1.2 2003-09-18 06:43:57 oops Exp $
.SH 이름
fileread

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "char * fileread (char * path);"

.SH 설명
파일을 내용을 반환한다.

.SH 반환값
반환된 값은 반드시 메모리 해제 (free) 를 해 주어야 한다.

.SH 예제
.nf
#include <olibc/libstring.h>

char *text;
char *path = "/etc/hosts";

text = fileread (path);
printf ("%s\\n", text);
free (text);
.fi

.SH 작성
2003.09.09 김정균 <http://www.oops.org>

.SH 버그
버그가 발견이 되면 http://www.oops.org 로 리포팅을 부탁한다.

.SH 저작권
BPL License v.1
.br
http://devel.oops.org/document/bpl 을 참고 하도록 한다.
