.TH get_whitespace(3) 2011-03-18 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man get_whitespace.3
.\" 2011-03-18 JoungKyun Kim <htt://oops.org>
.\" $Id: get_whitespace.3,v 1.7 2011-03-18 06:06:42 oops Exp $
.SH NAME
get_whitespace \- number of white space.

.SH SYNOPSIS
.B #include <olibc/libarg.h>
.sp
.BI "int get_whitespace (const char * string);"

.SH "Link library"
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
Get number of white space

.SH EXAMPLE
.nf
#include <olibc/libarg.h>

int main (void) {
    char * string = "a b c d e      f";

    printf ("## %d\\n", get_whitespace (string));
    return 0;
}
.fi

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
