.TH human_size(3) 2011-03-27 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man human_size.3
.\" 2011-03-27 JoungKyun Kim <htt://oops.org>
.\" $Id: human_size.3,v 1.8 2011-03-26 19:39:41 oops Exp $
.SH NAME
human_size \- convert number to human readable

.SH SYNOPSIS
.B #include <olibc/libstring.h>
.sp
.BI "char * human_size (ULong64 size, bool sub, bool unit);"

.SH "Link library"
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
.BI human_size()
와
.BI human_size_r()
apis are convert to unit for human readable. The return value
support decimal porint under 2 digits.

Now, these apis are supported byte and bit unit.

.TP
.B size
.br
The input 64bit integer

.TP
.B sub
.br
Set true, return with original size with 3 digit format.

.TP
.B unit
.br
Set true, caculation with Byte, else with Bit.

.SH "RETURN VALUE"
strping pointer of formatted string by human read.

The
.BI human_size()
api occurs internal error, the
.BI human_size() returns null. If the return string array
pointer is not null, the caller should deallocate this buffer
using
.BI free().

.SH EXAMPLE
.nf
#include <olibc/libstring.h>

int main (void) {
    long no = 123456789;
    char *data;

    data = human_size ((ULong64) no, 1, 0);
    printf ("%s\\n", data);
    if ( data != null )
        free (data);

    return 0;
}
.fi

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
