.TH is_strint(3) 2011-03-26 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man is_strint.3
.\" 2011-03-26 JoungKyun Kim <htt://oops.org>
.\" $Id$
.SH NAME
is_strint \- check the ascii value of a character whether is between 48 and 57

.SH SYNOPSIS
.B #include <olibc/libstring.h>
.sp
.BI "bool is_strint (char c);"

.SH Link library
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
The
.BI is_strint()
function check whether a given character has value between 48 and 57.

.TP
.B c
.br
A character for checking

.SH "RETURN VALUE"
The input character is integer, return 1, otherwise returns 0.

.SH EXAMPLE
.nf
#include <olibc/libstring.h>

int main (void) {
    char *str = "12c3";
    int i = 0;

    for (i=strlen (str) - 1; i >= 0; i--) {
        if ( is_strint (str[i]) ) {
            printf ("%c is int\\n", str[i]);
        } else {
            printf ("%c is not int\\n", str[i]);
        }
    }

    return 0;
}
.fi

.SH "SEE ALSO"
char2int(3) str2double(3) str2long(3)

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
