.TH microtime(1) 2003-08-31 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man microtime.1
.\" 2003-09-04 JoungKyun Kim <htt://www.oops.org>
.\" $Id: microtime.3,v 1.2 2003-09-18 06:43:57 oops Exp $
.SH 이름
microtime

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "double microtime(void);"

.SH 설명
현재의 microtime 을 구한다.

.SH 반환값
더블타입의 현재 마이크로 시간

.SH 예제
.nf
#include <olibc/libstring.h>

printf ("%f\\n", microtime);
.fi

.SH 작성
2003.09.04 김정균 <http://www.oops.org>

.SH 버그
버그가 발견이 되면 http://www.oops.org 로 리포팅을 부탁한다.

.SH 저작권
BPL License v.1
.br
http://devel.oops.org/document/bpl 을 참고 하도록 한다.
