.TH microtime(3) 2011-03-18 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man microtime.3
.\" 2011-03-18 JoungKyun Kim <htt://oops.org>
.\" $Id: microtime.3,v 1.6 2011-03-18 06:21:01 oops Exp $
.SH NAME
microtime \- get current micro seconds.

.SH SYNOPSIS
.B #include <olibc/libstring.h>
.sp
.BI "double microtime (void);"

.SH "Link library"
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
Return current micro seconds. If system support
.B realtime kernel
and builds with
.BI clock_gettime()
api, the
.BI microtime()
api support nano seconds.

On system that support both
.BI clock_gettime()
and
.BI gettimeofday()
,
.BI microtime()
api does not supported.

.SH "RETURN VALUE"
The current micro seconds with double type.

.SH EXAMPLE
.nf
#include <olibc/libtime.h>

int main (void) {
    printf ("%f\\n", microtime());
    return 0;
}
.fi

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
