.TH ofree_array(3) 2011-03-18 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man ofree_array.3
.\" 2011-03-18 JoungKyun Kim <htt://oops.org>
.\" $Id: ofree_array.3,v 1.6 2011-03-18 06:02:20 oops Exp $
.SH NAME
ofree_array - free memory of null terminating array

.SH SYNOPSIS
.B #include <olibc/libarg.h>
.sp
.BI "char * ofree_array (char ** array);"

.SH "Link library"
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
Free memory of null termination array that is created by the
.BI argv_make()
api.

.SH EXAMPLE
See also
.B man 3 argv_make

.SH "SEE ALSO"
argv_make(3)

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
