.TH preg_replace(1) 2004-02-19 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man preg_replace | less
.\" 2004-02-19 JoungKyun Kim <htt://oops.org>
.\" $Id: preg_replace.3,v 1.6 2011-03-16 11:17:40 oops Exp $
.SH 이름
preg_replace

.SH 사용법
.B #include <olibc/libpcre.h>
.sp
.BI "char * preg_replace (char *regex, char *replace, char *subject, int *retlen);"

.SH 라이브러리 링크
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
또는
.B libolibc.a
에는
.BI "LGPL2 symbol"
이 포함되어 있으므로 이 라이브러리를
링크하려면 LGPL2의 영향을 받는다. idn관련 api를 사용하지 않고, BSD 라이센스의 적용을
원한다면
.B liboc.so
나
.B liboc.a
를 이용해야 한다.

.SH 설명
.B preg_replace
함수는 정규식에 의하여 원하는 문자를 변환하는 함수이다. 정규식은
.B perl 호환
정규식을 따르며, php 의 preg_replace 함수와 동일하나, 배열을 지원하지 않으며,
e 옵션과 callback 이 지원되지 않는다.

UTF8 은 시스템의 pcrelib 에 의존을 한다.

.TP
.B regex
.br
정규식을 지정한다. 정규식은
.B "/정규식/옵션"
과 같이 지정을 한다.

.TP
.B replace
.br
정규식에 의하여 변경될 문자열을 지정을 한다.

.TP
.B subject
.br
정규식으로 체크할 원본 문자열을 지정한다.

.TP
.B retlen
.br
변경된 후의 문자열 길이를 반환한다.

.SH 반환값
이 함수가 리턴한 값은 메모리 해제(free)를 해 줘야 한다.

.SH 예제
.nf
#include <olibc/libpcre.h>

char *result;
int len;

result = preg_replace("/xx/i", "!!", "SeeEEeex", &len);
printf ("%s\\n", result);

free (result);
.fi

.SH 참조
preg_quote(1), preg_replace_arr(1), preg_grep(1)

.SH 작성
2004.02.19 김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
