.TH preg_match(1) 2003-09-14 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man preg_match.1
.\" 2003-09-14 JoungKyun Kim <htt://www.oops.org>
.SH 이름
preg_match

.SH 사용법
.B #include <olibc/libpcre.h>
.sp
.BI "int preg_match (char *regex, char *subject);"

.SH 설명
.B preg_match
는 정규식이 매치가 되면 1을 리턴하고, 매치 되지 않으면 0 을 리턴한다.

.TP
.B regex
.br
체크할 정규식을 지정

.TP
.B subject
.br
검사할 문자열

.SH 반환값
정수

.SH 예제
.nf
#include <olibc/libpcre.h>

char *x = "abcd1234\\\\n6943Aaa";
printf ("%d\\n", preg_match ("/[0-9][a-z]/i", x));

.fi

.SH 작성
2003.09.14 김정균 <http://www.oops.org>

.SH 버그
버그가 발견이 되면 http://www.oops.org 로 리포팅을 부탁한다.

.SH 저작권
BPL License v.1
.br
http://devel.oops.org/document/bpl 을 참고 하도록 한다.
