.TH setansi(3) 2011-03-26 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man setansi.3
.\" 2011-03-26 JoungKyun Kim <htt://oops.org>
.\" $Id$
.SH NAME
setansi \- Set ansi color

.SH SYNOPSIS
.B #include <olibc/libstring.h>
.sp
.BI "void setansi (FILE * stream, int color, bool noansi);"

.SH "Link library"
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
Print magic character of ansi color on the file stream. If you want to stop
ansi mode, recall this function with
.B ENDANSI
constant.

.TP
.B stream
.br
.B stdin, stdout or stderr,
and so on.

.TP
.B color
.br
olibc color constants. See also follows:

.B OC_ENDANSI 0
.br
.B OC_GRAY 30
.br
.B OC_BGRAY 40
.br
.B OC_RED 31
.br
.B OC_BRED 41
.br
.B OC_GREEN 32
.br
.B OC_BGREEN 42
.br
.B OC_YELLOW 33
.br
.B OC_BYELLOW 43
.br
.B OC_BLUE 34
.br
.B OC_BBLUE 44
.br
.B OC_MAGENTA 35
.br
.B OC_BMAGENTA 45
.br
.B OC_CYAN 36
.br
.B OC_BCYAN 46
.br
.B OC_WHITE 37
.br
.B OC_BWHITE 47

.TP
.B noansi
.br
Set true, this function don't operate.

.SH "RETURN VALUE"
없음

.SH EXAMPLE
.nf
#include <olibc/libstring.h>

int main (void) {
    char * path = "/vars";

    setansi (stdout, OC_GRAY, 0);
    printf ("ANY  : %d\\n", file_exists (path, OC_IS_NCHK));
    setansi (stdout, OC_ENDANSI, 0);
    setansi (stdout, OC_BLUE, 0);
    printf ("FILE : %d\\n", file_exists (path, OC_IS_FILE));
    setansi (stdout, OC_ENDANSI, 0);

    return 0;
}
.fi

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
