.TH setansi(1) 2004-02-19 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man setansi.1
.\" 2004-02-19 JoungKyun Kim <htt://oops.org>
.\" $Id: setansi.3,v 1.4 2009-10-29 13:24:33 oops Exp $
.SH 이름
setansi

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "int setansi(FILE *stream, int color, int mode);"

.SH 라이브러리 링크
.B gcc source -l liboc
.br

또는

.B gcc source -l libolibc
.br

libolibc 를 정적으로 링크할 경우에는 LGPL2 에 근거하여 사용이 가능하며, liboc 를
정적으로 링크할 경우에는 BPL 에 근거한다.

.SH 설명
파일 스트림의 출력 문자열의 색상을 지정한다. 이 함수를 사용한 후에,
다시 ENDANSI 상수를 이용하여 재호출을 해 줘야 한다.

.TP
.B stream
.br
색상을 출력할 표준출력/표준에러/파일스트림 을 지정한다.

.TP
.B color
.br
다음의 상수를 참고한다.

.B ENDANSI 0
.br
.B GRAY 1
.br
.B BGRAY 2
.br
.B RED 3
.br
.B BRED 4
.br
.B GREEN 5
.br
.B BGREEN 6
.br
.B YELLOW 7
.br
.B BYELLOW 8
.br
.B BLUE 9
.br
.B BBLUE 10
.br
.B MAGENTA 11
.br
.B BMAGENTA 12
.br
.B CYAN 13
.br
.B BCYAN 14
.br
.B WHITE 15
.br
.B BWHITE 16

.TP
.B noansi
.br
0 이 아니면, 이 함수가 아무런 작동을 하지 않도록 한다.

.SH 반환값
없음

.SH 예제
.nf
#include <olibc/libstring.h>

char *path = "/vars";

setansi (stdout, GRAY, 0);
printf ("ANY  : %d\\n", file_exists (path, _IS_NCHK));
setansi (stdout, ENDANSI, 0);
setansi (stdout, BLUE, 0);
printf ("FILE : %d\\n", file_exists (path, _IS_FILE));
setansi (stdout, ENDANSI, 0);
.fi

.SH 작성
2004.02.19 김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
