.TH strtoupper(1) 2011-02-10 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man strtoupper.1
.\" 2011-02-10 JoungKyun.Kim <htt://oops.org>
.\" $Id: strtoupper.3,v 1.5 2011-02-09 17:28:35 oops Exp $
.SH NAME
strtoupper \- convert a upper case to upper case

.SH USAGE
.B #include <olibc/libstring.h>
.sp
.BI "void strtoupper (char *str);"

.SH Link library
.B gcc source -loc
.br
or
.B gcc source -logc 
.br

If link with -logc, this object is follows LGPL2, but link with -loc, object is
follows BPL.

.SH DESCRIPTION
The strtoupper() function converts strings to upper case.
The given argument of strtoupper is changed.

.SH "RETURN VALUE"
None

.SH EXAMPLE
.nf
#include <olibc/libstring.h>

int main (void) {
    char data[5] = "DaTa";
    strtoupper (data);
    printf ("%s\\n", data);

    return 0;
}
.fi

.SH "SEE ALSO"
strtoupper(1)

.SH AUTHOR
Thu, 10 Feb 2011 JoungKyun.Kim

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
