.TH strtoupper(3) 2011-02-10 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man strtoupper.3
.\" 2011-02-10 JoungKyun.Kim <htt://oops.org>
.\" $Id: strtoupper.3,v 1.7 2011-03-08 17:48:56 oops Exp $
.SH NAME
strtoupper \- convert a upper case to upper case

.SH USAGE
.B #include <olibc/libstring.h>
.sp
.BI "void strtoupper (char * str);"

.SH Link library
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
The
.BI strtoupper()
function converts strings to upper case.

.TP
.B char * str
.br
The input string

.TP
The given argument of strtoupper is changed.

.SH "RETURN VALUE"
None

.SH EXAMPLE
.nf
#include <olibc/libstring.h>

int main (void) {
    char data[5] = "DaTa";
    strtoupper (data);
    printf ("%s\\n", data);

    return 0;
}
.fi

.SH "SEE ALSO"
strtoupper(3)

.SH AUTHOR
JoungKyun.Kim <http://oops.org/>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
