.TH writefile(3) 2011-03-16 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man writefile.3
.\" 2011-03-16 JoungKyun Kim <htt://oops.org>
.SH 이름
writefile \- Writes data to a file.

.SH SYNOPSIS
.B #include <olibc/libfile.h>
.sp
.BI "size_t writefile (const char * path, const char * data, size_t size, bool mode);"

.SH "Link library"
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
and
.B libolibc.a
include
.B "LGPL2 symbols,"
so links this library, your object or binary is follows LGPL2.
If you don't need idn library and, don't want LGPL 2 effects,
use
.B liboc.so
or
.B liboc.a
that follows BSD license.

.SH DESCRIPTION
Writes data to a file.

The
.BI writefile()
api is binary safe.

.TP
.B path
.br
Path to the file where to write the data.

.TP
.B data
.br
The data to write.

.TP
.B size
.br
The length of data

.TP
.B mode
Bool. Set true, append and set false, new file.

.SH "RETURN VALUE"
bool

.SH EXAMPLE
.nf
#include <olibc/libfile.h>

int main (void) {
    char *text = "asdf";
    char *path = "/etc/hosts";

    if ( writefile (path, text, strlen (text), 0) == false )
        printf ("failed\\n");
    else
        printf ("success\\n");

    return 0;
}
.fi

.SH "SEE ALSO"
readfile(3)

.SH AUTHOR
JoungKyun.Kim <http://oops.org>

.SH BUGS
Please report bug on QnA bulletin board on http://oops.org/
