.TH writefile(1) 2004-02-19 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man writefile.1
.\" 2004-02-19 JoungKyun Kim <htt://oops.org>
.SH 이름
writefile

.SH 사용법
.B #include <olibc/libfile.h>
.sp
.BI "int writefile (char * filename, char * str, int mode);"

.SH 라이브러리 링크
.B gcc source -l liboc
.br

또는

.B gcc source -l libolibc
.br

libolibc 를 정적으로 링크할 경우에는 LGPL2 에 근거하여 사용이 가능하며, liboc 를
정적으로 링크할 경우에는 BPL 에 근거한다.

.SH 설명
str 을 filename 에 기록한다. mode 가 1 이면, filename 이 존재할 경우
해당 파일에 이어서 작성을 하며, 0 이거나 해당 파일이 없으면, filename
을 새로 기록한다.

.SH 반환값
이 함수는 기록에 성공했을 경우 0을 반환하며, 실패했을 경우 -1 을 반환
한다.

.SH 예제
.nf
#include <olibc/libfile.h>

char *text = "asdf";
char *path = "/etc/hosts";

printf ("%d\\n", writefile (path, text, 0));
.fi

.SH 작성
2004.02.19 김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
