/** 
 * @file	acconfig.h
 * @brief	Template of olibc-config.h.in
 *
 * This file template file of olibc-config.h.in
 * that is generated by autoconf.
 *
 * @author	JoungKyun.Kim <http://oops.org>
 * $Date: 2011-04-09 15:54:19 $
 * $Revision: 1.7 $
 * @attention	Copyright (c) 2011 JoungKyun.Kim all rights reserved.
 */
/* $Id: acconfig.h,v 1.7 2011-04-09 15:54:19 oops Exp $ */
#ifndef OLIBC_CONFIG_H
#define OLIBC_CONFIG_H

#define OC_FILEBUF		4096
#define OC_LINEBUF		4096
#define OC_NETWBUF		1024

/* config.h:  a general config file */

@TOP@

@BOTTOM@

#define HAVE_LIBIDN 1
#define HAVE_LIBPCRE 1

#define ENABLE_NLS 1
#ifndef HAVE_SETLOCALE_H
#undef ENABLE_NLS
#endif

#ifndef HAVE_LIBINTL_H
#undef ENABLE_NLS
#endif

#endif /*  OLIBC_CONFIG_H */
