#!/bin/sh
#
# $Id: autogen,v 1.6 2011-02-06 15:11:19 oops Exp $
# require autoconf > 2.59 & automake > 1.8
#

aclocal -I ./m4 --force >& /dev/null && autoconf --force && autoheader --force && libtoolize --force
rm -rf autom4te* *~ aclocal.m4 config.guess config.sub ltmain.sh
touch install-sh

for i in config.guess config.sub ltmain.sh
do
    cp -af /usr/share/libtool/${i} ./
done

exit 0
