#!/bin/sh
#
# $Id: autogen,v 1.7 2011-04-09 15:54:19 oops Exp $
# require autoconf > 2.59 & automake > 1.8
#

opt=

[ "$1" = "--install" ] && opt="$1"

rm -f configure
autoreconf $opt

if [ -n "$opt" ]; then
	rm -rf po ABOUT-NLS
fi

exit 0
