.TH charset_conv(3) 2011-03-21 "Linux Manpage" "OOPS C Library's Manual"
.\" Process with
.\" nroff -man charset_conv.3
.\" 2011-03-21 JoungKyun Kim <htt://oops.org>
.\" $Id$
.SH 이름
charset_conv \- 문자셋 변경

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "char * charset_conv (const char *src, const char * from, const char * to)"

.SH 라이브러리 링크
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
또는
.B libolibc.a
에는
.BI "LGPL2 symbol"
이 포함되어 있으므로 이 라이브러리를
링크하려면 LGPL2의 영향을 받는다. idn관련 api를 사용하지 않고, BSD 라이센스의 적용을
원한다면
.B liboc.so
나
.B liboc.a
를 이용해야 한다.

.SH 설명
.BI charset_conv()
api는 문자열의 문자셋을 변경한다.

.TP
.B src
.br
주어진 소스 문자열
The input source string

.TP
.B from
.br
소스 문자열의 문자셋

.TP
.B to
.br
변경할 문제셋

.SH 반환값
변환된 문자열의 포인터를 반환한다. 내부적으로 에러가 발생을 하면
null을 반환한다. 만약 반환값이 null이 아니라면
.BI free()
api로 메모리를 반환해 주어야 한다.

.SH 예제
.nf
#include <olibc/libstring.h>

int main (void) {
    unsigned char src[5] = { 0, };
    char * p;

    // follow is EUC-KR "한글"
    sprintf (src, "%c%c%c%c", 0xc7, 0xd1, 0xb1, 0xdb);

    // convert EUC-KR to UTF-8
    p = charset_conv (src, "EUC-KR", "UTF-8");
    if ( p == null ) {
        printf ("failed\\n");
        exit (1);
    }

    printf ("%s\\n", p);
    free (p);
}
.fi

.SH 참조
is_utf8(3), is_ksc5601(3)

.SH 작성
김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org/ 로 리포팅을 부탁한다.
