.TH readfile(3) 2011-03-24 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man readfile.3
.\" 2011-03-24 JoungKyun Kim <htt://oops.org>
.\" $Id: readfile.3,v 1.4 2011-03-24 05:48:56 oops Exp $
.SH 이름
readfile \- 파일을 읽는다.

.SH 사용법
.B #include <olibc/libfile.h>
.sp
.BI "size_t readfile (const char * path, char ** buf);"

.SH 라이브러리 링크
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
또는
.B libolibc.a
에는
.BI "LGPL2 symbol"
이 포함되어 있으므로 이 라이브러리를
링크하려면 LGPL2의 영향을 받는다. idn관련 api를 사용하지 않고, BSD 라이센스의 적용을
원한다면
.B liboc.so
나
.B liboc.a
를 이용해야 한다.

.SH 설명
파일을 내용 읽어
.B buf
에 저장하고 읽은 길이를 반환한다.

.TP
.BI path
.br
읽을 파일의 경로를 지정한다.

.TP
.BI buf
.br
파일의 내용을 저장한다.
.BI readfile()
api 수행이
.B 실패
할 경우
.B null
값을 가지게 된디.

성공적으로 수행이 되었다면,
.B buf
는
.BI free()
api를 이용하여 메모리를 반환해 줘야 한다.

.SH 반환값
읽은 파일의 길이를 반환한다.

.SH 예제
.nf
#include <olibc/libfile.h>

int main (void) {
    char *text;
    char *path = "/etc/hosts";
    size_t len;

    len = readfile (path, &text);
    if ( text != null ) {
        printf ("%s\\n", text);
        free (text);
    } else {
        printf ("failed\\n");
    }

    return 0;
}
.fi

.SH 작성
김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
