.TH readfile(3) 2011-03-16 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man readfile.3
.\" 2011-03-16 JoungKyun Kim <htt://oops.org>
.\" $Id: readfile.3,v 1.1 2011-03-16 11:35:16 oops Exp $
.SH 이름
readfile \- 파일을 읽는다.
.br
fileread \- readfile의 alias

.SH 사용법
.B #include <olibc/libfile.h>
.sp
.BI "char * fileread (const char * path);"
.br
.BI "char * readfile (const char * path);"

.SH 라이브러리 링크
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
또는
.B libolibc.a
에는
.BI "LGPL2 symbol"
이 포함되어 있으므로 이 라이브러리를
링크하려면 LGPL2의 영향을 받는다. idn관련 api를 사용하지 않고, BSD 라이센스의 적용을
원한다면
.B liboc.so
나
.B liboc.a
를 이용해야 한다.

.SH 설명
파일을 내용을 반환한다.

.SH 반환값
파일의 내용을 담은 포인터를 반환한다. 반환된 값은 반드시 메모리
해제 (free) 를 해 주어야 한다. 파일 읽기를 실패했을 경우, NULL을
반환한다.

.BI fileread()
는 다음 버전 부터 없어진다. readfile을 사용하도록 한다.

.SH 예제
.nf
#include <olibc/libfile.h>

int main (void) {
    char *text;
    char *path = "/etc/hosts";

    text = fileread (path);
    printf ("%s\\n", text);
    free (text);

    return 0;
}
.fi

.SH 작성
김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
