.TH setansi(3) 2011-03-19 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man setansi.3
.\" 2011-03-19 JoungKyun Kim <htt://oops.org>
.\" $Id: setansi.3,v 1.1.2.1 2011-03-29 18:24:11 oops Exp $
.SH 이름
setansi \- ansi 색상 설정

.SH 사용법
.B #include <olibc/libstring.h>
.sp
.BI "void setansi (FILE * stream, int color, bool noansi);"

.SH 라이브러리 링크
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
또는
.B libolibc.a
에는
.BI "LGPL2 symbol"
이 포함되어 있으므로 이 라이브러리를
링크하려면 LGPL2의 영향을 받는다. idn관련 api를 사용하지 않고,
BSD 라이센스의 적용을 원한다면
.B liboc.so
나
.B liboc.a
를 이용해야 한다.

.SH 설명
파일 스트림의 출력 문자열의 색상을 지정한다. 이 함수를 사용한 후에,
다시 ENDANSI 상수를 이용하여 재호출을 해 줘야 한다.

.TP
.B stream
.br
색상을 출력할
.B 표준출력/표준에러/파일스트림
을 지정한다.

.TP
.B color
.br
다음의 상수를 참고한다.

.B OC_ENDANSI 0
.br
.B OC_GRAY 30
.br
.B OC_BGRAY 40
.br
.B OC_RED 31
.br
.B OC_BRED 41
.br
.B OC_GREEN 31
.br
.B OC_BGREEN 42
.br
.B OC_YELLOW 31
.br
.B OC_BYELLOW 43
.br
.B OC_BLUE 31
.br
.B OC_BBLUE 44
.br
.B OC_MAGENTA 35
.br
.B OC_BMAGENTA 45
.br
.B OC_CYAN 36
.br
.B OC_BCYAN 46
.br
.B OC_WHITE 37
.br
.B OC_BWHITE 47

.TP
.B noansi
.br
true로 설정이 되면, 이 함수는 아무런 작동을 하지 않는다.

.SH 반환값
없음

.SH 예제
.nf
#include <olibc/libstring.h>

int main (void) {
    char * path = "/vars";

    setansi (stdout, GRAY, 0);
    printf ("ANY  : %d\\n", file_exists (path, _IS_NCHK));
    setansi (stdout, ENDANSI, 0);
    setansi (stdout, BLUE, 0);
    printf ("FILE : %d\\n", file_exists (path, _IS_FILE));
    setansi (stdout, ENDANSI, 0);

    return 0;
}
.fi

.SH 작성
김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
