.TH writefile(3) 2011-03-24 "Linux Manpage" "OOPS Library's Manual"
.\" Process with
.\" nroff -man writefile.3
.\" 2011-03-24 JoungKyun Kim <htt://oops.org>
.SH 이름
writefile \- 파일에 데이터를 기록

.SH 사용법
.B #include <olibc/libfile.h>
.sp
.BI "size_t writefile (const char * path, CChar * data, size_t size, bool mode);"

.SH 라이브러리 링크
.B \-loc
or
.B \-lolibc
.br

.B libolibc.so
또는
.B libolibc.a
에는
.BI "LGPL2 symbol"
이 포함되어 있으므로 이 라이브러리를
링크하려면 LGPL2의 영향을 받는다. idn관련 api를 사용하지 않고, BSD 라이센스의 적용을
원한다면
.B liboc.so
나
.B liboc.a
를 이용해야 한다.

.SH 설명
data를 path에 기록한다. mode 가 1 이면, filename 이 존재할 경우
해당 파일에 이어서 작성을 하며, 0 이거나 해당 파일이 없으면, filename
을 새로 기록한다.

.BI writefile()
API는 binary safe를 보장한다.

.TP
.B path
.br
기록할 파일 경로

.TP
.B data
.br
파일에 기록할 데이터

.TP
.B size
.br
data의 길이

.TP
.B mode
true로 설정되고 파일이 존재할 경우, 기존의 내용에 이어서 기록을 하고,
false로 설정되거나 파일이 존재하지 않을 경우 신규 파일로 path를 만들어
기록한다.

.SH 반환값
bool

.SH 예제
.nf
#include <olibc/libfile.h>

int main (void) {
    char *text = "asdf";
    char *path = "/etc/hosts";

    if ( writefile (path, text, strlen (text), 0) == false )
        printf ("failed\\n");
    else
        printf ("success\\n");

    return 0;
}
.fi

.SH 참고
readfile(3)

.SH 작성
김정균 <http://oops.org>

.SH 버그
버그가 발견이 되면 http://oops.org 로 리포팅을 부탁한다.
